import SampleImg from '../assets/images/8-10.jpg';

const programs = [
    {
      id:0,  
      name: "Buddhist Program",
      startTime: "05:00:00 am",
      endTime: "05:29:59 am",
      category: "Religous",
      img:SampleImg,
    },
    {
      id:1,    
      name: "Catholic Program",
      startTime: "05:29:59 am",
      endTime: "05:59:59 am",
      category: "Religous",
      img:SampleImg,
    },
    {
        id:2,    
      name: "Ayubowan Seth",
      startTime: "06:00:00 am",
      endTime: "07:29:59 am",
      category: "Entertainment",
      img:SampleImg,
    },
    {
      id:3,  
      name: "Paththara Wisthara",
      startTime: "07:30:00 am",
      endTime: "07:59:59 am",
      description: "Newspaper",
      img:SampleImg,
    },
    {
        id:4,  
      name: "Ata Dahaya",
      startTime: "08:00:00 am",
      endTime: "09:59:59 am",
      description: "Entertainment",
      img:SampleImg,
    },
    {
      id:5,  
      name: "Gee Sandalla",
      startTime: "10:00:00 am",
      endTime: "11:59:59 am",
      description: "Entertainment",
      img:SampleImg,
    },
    {
        id:6,    
      name: "ThunKala Aradhanwa ",
      startTime: "12:00:00 pm",
      endTime: "12:59:59 pm",
      description: "Religous",
      img:SampleImg,
    },
    {
        id:7,
      name: "Back-to-Back",
      startTime: "01:00:00 pm",
      endTime: "01:59:59 pm",
      description: "Entertainment",
      img:SampleImg,
    },
    {
      id:8,
    name: "Back-to-Back",
    startTime: "02:00:00 pm",
    endTime: "02:59:59 pm",
    description: "Entertainment",
    img:SampleImg,
  },
    {
        id:9,    
      name: "Daily Mass",
      startTime: "03:00:00 pm",
      endTime: "03:59:59 pm",
      description: "Religous",
      img:SampleImg,
    },
    {
      id:10,   
      name: "Song PlayList",
      startTime: "04:00:00 pm",
      endTime: "04:59:59 pm",
      description: "Idle",
      img:SampleImg,
    },
    {
        id:11,
      name: "Seth Evening Request",
      startTime: "05:00:00 pm",
      endTime: "06:59:59 pm",
      description: "Entertainment",
      img:SampleImg,
    },
    {
        id:12,
      name: "Catholic",
      startTime: "07:00:00 pm",
      endTime: "07:59:59 pm",
      description: "Religous",
      img:SampleImg,
    },
    {
      id:13,  
      name: "Emmaus",
      startTime: "08:00:00 pm",
      endTime: "08:59:59 pm",
      description: "Religous",
      img:SampleImg,
    },
    {
      id:14,  
      name: "Catholic",
      startTime: "09:00:00 pm",
      endTime: "03:59:59 am",
      description: "Religous",
      img:SampleImg,
    },
  ];
export default programs;